services:
  frontend-dev:
    container_name: mapa-front-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # --- Hot Reloading ---
    volumes:
      # 1. Monta el directorio actual ('.') en '/usr/src/app' del contenedor.
      - .:/usr/src/app
      # 2. Crea un "volumen anónimo" para node_modules.
      #    Evita que la carpeta node_modules sobrescriba la que se instaló DENTRO del contenedor.
      - /usr/src/app/node_modules
    # Mantiene el contenedor corriendo interactivamente.
    stdin_open: true
    tty: true